name: test_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Riverpod
  flutter_hooks: ^0.18.2
  hooks_riverpod: ^2.0.0-dev.0
  freezed_annotation:

  # Setting
  app_settings: ^4.1.1

  # Other
  package_info: ^2.0.2
  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Static analysis
  pedantic_mono: ^1.14.0+1

  # Serializer
  json_serializable:

  # Code generator
  build_runner:
  freezed: ^1.1.1

flutter:

  uses-material-design: true